CREATE TABLE `wp_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_terms` DISABLE KEYS */;
INSERT INTO `wp_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('2', 'Product Category', 'product-category', '0');
INSERT INTO `wp_terms` VALUES('3', 'simple', 'simple', '0');
INSERT INTO `wp_terms` VALUES('4', 'grouped', 'grouped', '0');
INSERT INTO `wp_terms` VALUES('5', 'variable', 'variable', '0');
INSERT INTO `wp_terms` VALUES('6', 'external', 'external', '0');
INSERT INTO `wp_terms` VALUES('7', 'pending', 'pending', '0');
INSERT INTO `wp_terms` VALUES('8', 'failed', 'failed', '0');
INSERT INTO `wp_terms` VALUES('9', 'on-hold', 'on-hold', '0');
INSERT INTO `wp_terms` VALUES('10', 'processing', 'processing', '0');
INSERT INTO `wp_terms` VALUES('11', 'completed', 'completed', '0');
INSERT INTO `wp_terms` VALUES('12', 'refunded', 'refunded', '0');
INSERT INTO `wp_terms` VALUES('13', 'cancelled', 'cancelled', '0');
INSERT INTO `wp_terms` VALUES('17', 'Version History', 'version-history', '0');
INSERT INTO `wp_terms` VALUES('18', 'Team Foundation Server', 'team-foundation-server', '0');
INSERT INTO `wp_terms` VALUES('19', 'Compatibility', 'compatibility', '0');
INSERT INTO `wp_terms` VALUES('20', 'Time Management', 'time-management', '0');
INSERT INTO `wp_terms` VALUES('21', 'Internals', 'internals', '0');
/*!40000 ALTER TABLE `wp_terms` ENABLE KEYS */;
