CREATE TABLE `wp_term_taxonomy` (  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `taxonomy` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',  `count` bigint(20) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_taxonomy_id`),  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),  KEY `taxonomy` (`taxonomy`)) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_term_taxonomy` DISABLE KEYS */;
INSERT INTO `wp_term_taxonomy` VALUES('1', '1', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('2', '2', 'wpsc_product_category', '', '0', '1');
INSERT INTO `wp_term_taxonomy` VALUES('3', '3', 'product_type', '', '0', '2');
INSERT INTO `wp_term_taxonomy` VALUES('4', '4', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('5', '5', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('6', '6', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('7', '7', 'shop_order_status', '', '0', '5');
INSERT INTO `wp_term_taxonomy` VALUES('8', '8', 'shop_order_status', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('9', '9', 'shop_order_status', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('10', '10', 'shop_order_status', '', '0', '10');
INSERT INTO `wp_term_taxonomy` VALUES('11', '11', 'shop_order_status', '', '0', '8');
INSERT INTO `wp_term_taxonomy` VALUES('12', '12', 'shop_order_status', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('13', '13', 'shop_order_status', '', '0', '3');
INSERT INTO `wp_term_taxonomy` VALUES('17', '17', 'category', '', '0', '16');
INSERT INTO `wp_term_taxonomy` VALUES('18', '18', 'category', '', '0', '3');
INSERT INTO `wp_term_taxonomy` VALUES('19', '19', 'category', '', '0', '8');
INSERT INTO `wp_term_taxonomy` VALUES('20', '20', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('21', '21', 'category', '', '0', '3');
/*!40000 ALTER TABLE `wp_term_taxonomy` ENABLE KEYS */;
