CREATE TABLE `wp_usermeta` (  `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `meta_value` longtext COLLATE utf8mb4_unicode_ci,  PRIMARY KEY (`umeta_id`),  KEY `user_id` (`user_id`),  KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB AUTO_INCREMENT=1753 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_usermeta` DISABLE KEYS */;
INSERT INTO `wp_usermeta` VALUES('1', '1', 'first_name', 'Marc');
INSERT INTO `wp_usermeta` VALUES('2', '1', 'last_name', 'Schaeffler');
INSERT INTO `wp_usermeta` VALUES('3', '1', 'nickname', 'marcs');
INSERT INTO `wp_usermeta` VALUES('4', '1', 'description', '');
INSERT INTO `wp_usermeta` VALUES('5', '1', 'rich_editing', 'true');
INSERT INTO `wp_usermeta` VALUES('6', '1', 'comment_shortcuts', 'false');
INSERT INTO `wp_usermeta` VALUES('7', '1', 'admin_color', 'fresh');
INSERT INTO `wp_usermeta` VALUES('8', '1', 'use_ssl', '0');
INSERT INTO `wp_usermeta` VALUES('9', '1', 'show_admin_bar_front', 'true');
INSERT INTO `wp_usermeta` VALUES('10', '1', 'wp_capabilities', 'a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `wp_usermeta` VALUES('11', '1', 'wp_user_level', '10');
INSERT INTO `wp_usermeta` VALUES('12', '1', 'dismissed_wp_pointers', 'wp330_toolbar,wp330_saving_widgets,wp340_choose_image_from_library,wp340_customize_current_theme_link,wp350_media,wp360_revisions,wp360_locks,wp390_widgets,wp410_dfw');
INSERT INTO `wp_usermeta` VALUES('13', '1', 'show_welcome_panel', '0');
INSERT INTO `wp_usermeta` VALUES('14', '1', 'wp_dashboard_quick_press_last_post_id', '1287');
INSERT INTO `wp_usermeta` VALUES('15', '1', '_wpsc_customer_profile', 'a:6:{s:4:\"cart\";s:1036:\"O:9:\"wpsc_cart\":37:{s:16:\"delivery_country\";b:0;s:16:\"selected_country\";b:0;s:15:\"delivery_region\";b:0;s:15:\"selected_region\";b:0;s:24:\"selected_shipping_method\";N;s:24:\"selected_shipping_option\";N;s:24:\"selected_shipping_amount\";N;s:6:\"coupon\";N;s:14:\"tax_percentage\";N;s:9:\"unique_id\";s:40:\"ac6753df0313fc5c9a4bdf193ed52f831fa3b993\";s:6:\"errors\";a:0:{}s:9:\"total_tax\";N;s:13:\"base_shipping\";N;s:19:\"total_item_shipping\";N;s:14:\"total_shipping\";N;s:8:\"subtotal\";N;s:11:\"total_price\";N;s:13:\"uses_shipping\";N;s:13:\"is_incomplete\";b:1;s:10:\"cart_items\";a:0:{}s:9:\"cart_item\";N;s:15:\"cart_item_count\";i:0;s:17:\"current_cart_item\";i:-1;s:11:\"in_the_loop\";b:0;s:16:\"shipping_methods\";b:0;s:15:\"shipping_method\";N;s:21:\"shipping_method_count\";i:1;s:23:\"current_shipping_method\";i:-1;s:18:\"in_the_method_loop\";b:0;s:15:\"shipping_quotes\";a:0:{}s:14:\"shipping_quote\";N;s:20:\"shipping_quote_count\";i:0;s:22:\"current_shipping_quote\";i:-1;s:17:\"in_the_quote_loop\";b:0;s:12:\"coupons_name\";s:0:\"\";s:14:\"coupons_amount\";i:0;s:15:\"shipping_option\";N;}\";s:16:\"shipping_country\";b:0;s:15:\"billing_country\";b:0;s:15:\"shipping_region\";b:0;s:14:\"billing_region\";b:0;s:40:\"category_shipping_target_market_conflict\";b:0;}');
INSERT INTO `wp_usermeta` VALUES('16', '1', 'meta-box-order_wpsc-product', 'a:3:{s:4:\"side\";s:142:\"submitdiv,tagsdiv-product_tag,wpsc_product_categorydiv,postimagediv,wpsc_price_control_forms,wpsc_stock_control_forms,wpsc_product_taxes_forms\";s:6:\"normal\";s:199:\"wpsc_product_variation_forms,wpsc_product_external_link_forms,wpsc_additional_desc,wpsc_product_download_forms,wpsc_product_image_forms,wpsc_product_shipping_forms,wpsc_product_advanced_forms,slugdiv\";s:8:\"advanced\";s:0:\"\";}');
INSERT INTO `wp_usermeta` VALUES('17', '1', 'screen_layout_wpsc-product', '2');
INSERT INTO `wp_usermeta` VALUES('19', '1', 'managenav-menuscolumnshidden', 'a:3:{i:0;s:11:\"css-classes\";i:1;s:3:\"xfn\";i:2;s:11:\"description\";}');
INSERT INTO `wp_usermeta` VALUES('20', '1', 'metaboxhidden_nav-menus', 'a:5:{i:0;s:8:\"add-post\";i:1;s:11:\"add-product\";i:2;s:12:\"add-post_tag\";i:3;s:15:\"add-product_cat\";i:4;s:15:\"add-product_tag\";}');
INSERT INTO `wp_usermeta` VALUES('21', '1', 'nav_menu_recently_edited', '15');
INSERT INTO `wp_usermeta` VALUES('22', '1', '_order_count', '');
INSERT INTO `wp_usermeta` VALUES('45', '1', 'wp_user-settings', 'hidetb=1&libraryContent=browse&editor=tinymce&wplink=1&ed_size=204&align=none&urlbutton=none&posts_list_mode=list&post_dfw=off');
INSERT INTO `wp_usermeta` VALUES('46', '1', 'wp_user-settings-time', '1434450745');
INSERT INTO `wp_usermeta` VALUES('47', '1', 'closedpostboxes_dlm_download', 'a:0:{}');
INSERT INTO `wp_usermeta` VALUES('48', '1', 'metaboxhidden_dlm_download', 'a:1:{i:0;s:7:\"slugdiv\";}');
INSERT INTO `wp_usermeta` VALUES('142', '1', 'billing_first_name', 'Marc');
INSERT INTO `wp_usermeta` VALUES('143', '1', 'billing_last_name', 'Schaeffler');
INSERT INTO `wp_usermeta` VALUES('144', '1', 'billing_company', '');
INSERT INTO `wp_usermeta` VALUES('145', '1', 'billing_address_1', 'Teststr. 12');
INSERT INTO `wp_usermeta` VALUES('146', '1', 'billing_address_2', '');
INSERT INTO `wp_usermeta` VALUES('147', '1', 'billing_city', 'Munich');
INSERT INTO `wp_usermeta` VALUES('148', '1', 'billing_postcode', '80796');
INSERT INTO `wp_usermeta` VALUES('149', '1', 'billing_state', '');
INSERT INTO `wp_usermeta` VALUES('150', '1', 'billing_country', 'DE');
INSERT INTO `wp_usermeta` VALUES('151', '1', 'billing_phone', '');
INSERT INTO `wp_usermeta` VALUES('152', '1', 'billing_email', 'marc@berichthaus.com');
INSERT INTO `wp_usermeta` VALUES('153', '1', 'shipping_first_name', 'Marc');
INSERT INTO `wp_usermeta` VALUES('154', '1', 'shipping_last_name', 'Schaeffler');
INSERT INTO `wp_usermeta` VALUES('155', '1', 'shipping_company', '');
INSERT INTO `wp_usermeta` VALUES('156', '1', 'shipping_address_1', 'Teststr. 12');
INSERT INTO `wp_usermeta` VALUES('157', '1', 'shipping_address_2', '');
INSERT INTO `wp_usermeta` VALUES('158', '1', 'shipping_city', 'Munich');
INSERT INTO `wp_usermeta` VALUES('159', '1', 'shipping_postcode', '80796');
INSERT INTO `wp_usermeta` VALUES('160', '1', 'shipping_state', '');
INSERT INTO `wp_usermeta` VALUES('161', '1', 'shipping_country', 'DE');
INSERT INTO `wp_usermeta` VALUES('214', '1', 'zendesk_user_options', 'a:4:{s:8:\"username\";s:25:\"schaeffler@berichthaus.de\";s:8:\"password\";s:8:\"sotheb98\";s:5:\"roles\";i:2;s:12:\"default_view\";a:2:{s:2:\"id\";i:41186587;s:5:\"title\";s:21:\"Your unsolved tickets\";}}');
INSERT INTO `wp_usermeta` VALUES('215', '1', 'closedpostboxes_dashboard', 'a:2:{i:0;s:21:\"dashboard_quick_press\";i:1;s:17:\"dashboard_primary\";}');
INSERT INTO `wp_usermeta` VALUES('216', '1', 'metaboxhidden_dashboard', 'a:4:{i:0;s:19:\"dashboard_right_now\";i:1;s:36:\"woocommerce_dashboard_recent_reviews\";i:2;s:21:\"dashboard_quick_press\";i:3;s:17:\"dashboard_primary\";}');
INSERT INTO `wp_usermeta` VALUES('217', '1', 'meta-box-order_dashboard', 'a:4:{s:6:\"normal\";s:81:\"dashboard_right_now,google-analytics-summary,woocommerce_dashboard_recent_reviews\";s:4:\"side\";s:82:\"dashboard_quick_press,pb_backupbuddy_stats,dashboard_primary,dlm_popular_downloads\";s:7:\"column3\";s:28:\"woocommerce_dashboard_status\";s:7:\"column4\";s:18:\"dashboard_activity\";}');
INSERT INTO `wp_usermeta` VALUES('218', '1', 'screen_layout_dashboard', '2');
INSERT INTO `wp_usermeta` VALUES('219', '1', 'closedpostboxes_post', 'a:0:{}');
INSERT INTO `wp_usermeta` VALUES('220', '1', 'metaboxhidden_post', 'a:6:{i:0;s:12:\"revisionsdiv\";i:1;s:11:\"postexcerpt\";i:2;s:13:\"trackbacksdiv\";i:3;s:11:\"commentsdiv\";i:4;s:7:\"slugdiv\";i:5;s:9:\"authordiv\";}');
INSERT INTO `wp_usermeta` VALUES('278', '1', 'closedpostboxes_page', 'a:0:{}');
INSERT INTO `wp_usermeta` VALUES('279', '1', 'metaboxhidden_page', 'a:7:{i:0;s:12:\"revisionsdiv\";i:1;s:10:\"postcustom\";i:2;s:16:\"commentstatusdiv\";i:3;s:11:\"commentsdiv\";i:4;s:7:\"slugdiv\";i:5;s:9:\"authordiv\";i:6;s:27:\"prima-metabox-page-template\";}');
INSERT INTO `wp_usermeta` VALUES('295', '1', 'paying_customer', '1');
INSERT INTO `wp_usermeta` VALUES('296', '1', '_money_spent', '');
INSERT INTO `wp_usermeta` VALUES('305', '5', '_order_count', '');
INSERT INTO `wp_usermeta` VALUES('306', '5', '_money_spent', '');
INSERT INTO `wp_usermeta` VALUES('397', '17', 'first_name', 'Marc WPLive');
INSERT INTO `wp_usermeta` VALUES('398', '17', 'last_name', 'Schaeffler WPLive');
INSERT INTO `wp_usermeta` VALUES('399', '17', 'nickname', 'marcs410');
INSERT INTO `wp_usermeta` VALUES('400', '17', 'description', '');
INSERT INTO `wp_usermeta` VALUES('401', '17', 'rich_editing', 'true');
INSERT INTO `wp_usermeta` VALUES('402', '17', 'comment_shortcuts', 'false');
INSERT INTO `wp_usermeta` VALUES('403', '17', 'admin_color', 'fresh');
INSERT INTO `wp_usermeta` VALUES('404', '17', 'use_ssl', '0');
INSERT INTO `wp_usermeta` VALUES('405', '17', 'show_admin_bar_front', 'true');
INSERT INTO `wp_usermeta` VALUES('406', '17', 'wp_capabilities', 'a:1:{s:8:\"customer\";b:1;}');
INSERT INTO `wp_usermeta` VALUES('407', '17', 'wp_user_level', '0');
INSERT INTO `wp_usermeta` VALUES('408', '17', 'dismissed_wp_pointers', 'wp350_media,wp360_revisions,wp360_locks,wp390_widgets');
INSERT INTO `wp_usermeta` VALUES('409', '17', 'billing_country', 'DE');
INSERT INTO `wp_usermeta` VALUES('410', '17', 'billing_first_name', 'Marc WPLive');
INSERT INTO `wp_usermeta` VALUES('411', '17', 'billing_last_name', 'Schaeffler WPLive');
INSERT INTO `wp_usermeta` VALUES('412', '17', 'billing_company', 'Berichthaus WPLive');
INSERT INTO `wp_usermeta` VALUES('413', '17', 'billing_address_1', 'Destouchesstr. 68 WPLive');
INSERT INTO `wp_usermeta` VALUES('414', '17', 'billing_postcode', '80796');
INSERT INTO `wp_usermeta` VALUES('415', '17', 'billing_city', 'München WPLive');
INSERT INTO `wp_usermeta` VALUES('416', '17', 'billing_state', '');
INSERT INTO `wp_usermeta` VALUES('417', '17', 'billing_email', 'marcs410@gmx.de');
INSERT INTO `wp_usermeta` VALUES('418', '17', 'wc_fb_client_id', '24305');
INSERT INTO `wp_usermeta` VALUES('420', '17', '_order_count', '');
INSERT INTO `wp_usermeta` VALUES('421', '17', '_money_spent', '');
INSERT INTO `wp_usermeta` VALUES('422', '8', '_order_count', '');
INSERT INTO `wp_usermeta` VALUES('423', '8', '_money_spent', '');
INSERT INTO `wp_usermeta` VALUES('425', '1', 'closedpostboxes_attachment', 'a:0:{}');
INSERT INTO `wp_usermeta` VALUES('426', '1', 'metaboxhidden_attachment', 'a:3:{i:0;s:16:\"commentstatusdiv\";i:1;s:7:\"slugdiv\";i:2;s:9:\"authordiv\";}');
INSERT INTO `wp_usermeta` VALUES('545', '1', 'wc_fb_client_id', '109122');
INSERT INTO `wp_usermeta` VALUES('1736', '1', '_woocommerce_persistent_cart', 'a:1:{s:4:\"cart\";a:1:{s:32:\"4e732ced3463d06de0ca9a15b6153677\";a:10:{s:10:\"product_id\";i:26;s:12:\"variation_id\";s:0:\"\";s:9:\"variation\";s:0:\"\";s:8:\"quantity\";i:555;s:9:\"discounts\";a:6:{s:2:\"by\";a:1:{i:0;s:16:\"advanced_product\";}s:6:\"set_id\";s:17:\"set_53305680dcdd5\";s:10:\"price_base\";s:2:\"96\";s:13:\"display_price\";i:96;s:14:\"price_adjusted\";d:72;s:17:\"applied_discounts\";a:1:{i:0;a:4:{s:2:\"by\";s:16:\"advanced_product\";s:6:\"set_id\";s:17:\"set_53305680dcdd5\";s:10:\"price_base\";s:2:\"96\";s:14:\"price_adjusted\";d:72;}}}s:10:\"line_total\";d:39960;s:8:\"line_tax\";i:0;s:13:\"line_subtotal\";d:39960;s:17:\"line_subtotal_tax\";i:0;s:13:\"line_tax_data\";a:2:{s:5:\"total\";a:0:{}s:8:\"subtotal\";a:0:{}}}}}');
INSERT INTO `wp_usermeta` VALUES('1738', '1', 'wp_media_library_mode', 'list');
INSERT INTO `wp_usermeta` VALUES('1740', '1', 'session_tokens', 'a:1:{s:64:\"acb30ba9d0420c274c1452c4fc37e38eb23341d57cd2da27dac9bd0281c66a47\";a:4:{s:10:\"expiration\";i:1444998938;s:2:\"ip\";s:15:\"217.254.139.154\";s:2:\"ua\";s:110:\"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36\";s:5:\"login\";i:1444826138;}}');
INSERT INTO `wp_usermeta` VALUES('1741', '18', 'nickname', 'eva');
INSERT INTO `wp_usermeta` VALUES('1742', '18', 'first_name', 'eva');
INSERT INTO `wp_usermeta` VALUES('1743', '18', 'last_name', '');
INSERT INTO `wp_usermeta` VALUES('1744', '18', 'description', '');
INSERT INTO `wp_usermeta` VALUES('1745', '18', 'rich_editing', 'true');
INSERT INTO `wp_usermeta` VALUES('1746', '18', 'comment_shortcuts', 'false');
INSERT INTO `wp_usermeta` VALUES('1747', '18', 'admin_color', 'fresh');
INSERT INTO `wp_usermeta` VALUES('1748', '18', 'use_ssl', '0');
INSERT INTO `wp_usermeta` VALUES('1749', '18', 'show_admin_bar_front', 'true');
INSERT INTO `wp_usermeta` VALUES('1750', '18', 'wp_capabilities', 'a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `wp_usermeta` VALUES('1751', '18', 'wp_user_level', '10');
INSERT INTO `wp_usermeta` VALUES('1752', '18', 'dismissed_wp_pointers', '');
/*!40000 ALTER TABLE `wp_usermeta` ENABLE KEYS */;
